# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/web/main.go"
  bin = "tmp/main.exe"
  exclude_dir = ["assets", "tmp", "vendor", "docs"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  log = "build-errors.log"
  stop_on_error = true
  delay = 1000

[run]
  cmd = ""
  args = []
  env = ["ENV=development"]
  env_file = ".env"

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
  print_logs = true
  notify_on_error = true